[package]
name = "nvim-rs"
version = "0.1.1-alpha.0"
license = "LGPL-3.0"
authors = ["KillTheMule <KillTheMule@users.noreply.github.com"]
description = "A library for writing neovim rpc clients"
repository = "https://github.com/KillTheMule/nvim-rs"
readme = "README.md"
categories = ["api-bindings"]
keywords = ["neovim", "nvim", "rpc", "msgpack"]
exclude = [
  "neovim/*",
  ".travis.yml",
  "appveyor.yml",
  ".git",
  ".gitignore",
  ".gitmodules",
  "build.ps1"
]
edition = "2018"

[features]
use_tokio = []

[lib]
bench = false

[dependencies]
rmp = "0.8.9"
rmpv = "0.4.3"
log = "0.4"
tokio = { version = "0.2.3", features = ["sync", "rt-core", "macros", "io-util", "tcp", "uds", "process", "io-std", "dns", "rt-threaded", "io-driver", "fs"] }
async-trait = "0.1.18"
futures = { version = "0.3.1", features = ["io-compat"] }

[dev-dependencies]
tempdir = "0.3"
criterion = "0.3.0"

[profile.bench]
lto = true
debug = true

[[bench]]
name = "rpc"
harness = false
