[package]
name = "nvim-rs"
version = "0.1.1-alpha.0"
license = "LGPL-3.0"
authors = ["KillTheMule <KillTheMule@users.noreply.github.com"]
description = "A library for writing neovim rpc clients"
repository = "https://github.com/KillTheMule/nvim-rs"
readme = "README.md"
categories = ["api-bindings"]
keywords = ["neovim", "nvim", "rpc", "msgpack"]
exclude = [
  "neovim/*",
  ".travis.yml",
  "appveyor.yml",
  ".git",
  ".gitignore",
  ".gitmodules",
  "build.ps1"
]
edition = "2018"

[features]
use_tokio = ["tokio", "pin-project"]
use_async-std = ["async-std"]
use_neovim_lib = ["neovim-lib"]
localspawn = []
use_gio = ["gio", "glib", "gio-sys", "localspawn", "async-std"]

[lib]
bench = false

[dependencies]
rmp = "0.8.9"
rmpv = "0.4.3"
log = "0.4.8"
async-trait = "0.1.22"
futures = { version = "0.3.1", features = ["io-compat"] }
tokio = { version = "0.2.8", features = ["sync", "rt-core", "macros", "io-util", "tcp", "uds", "process", "io-std", "dns", "rt-threaded", "io-driver", "fs"] , optional = true}
pin-project = { version = "0.4.6", optional = true }
async-std = { version = "1.4.0", features = ["attributes"], optional = true }
neovim-lib = { version = "0.6.1", optional = true }
gio = { version = "0.8.0", optional = true }
glib = { version = "0.9.1", optional = true }
gio-sys = { version = "0.9.1", optional = true }

[dev-dependencies]
tempdir = "0.3"
criterion = "0.3.0"

[profile.bench]
lto = true
debug = true

[[bench]]
name = "rpc_tokio"
harness = false
required-features = ["use_tokio"]

[[example]]
name = "handler_drop"
required-features = ["use_tokio"]

[[example]]
name = "quitting"
required-features = ["use_tokio"]

[[example]]
name = "quitting_gio"
required-features = ["use_gio", "unix"]

[[example]]
name = "scorched_earth"
required-features = ["use_tokio"]

[[example]]
name = "scorched_earth_as"
required-features = ["use_async-std"]

[[example]]
name = "scorched_earth_gio"
required-features = ["use_gio"]

[[example]]
name = "bench_tokio"
required-features = ["use_tokio"]

[[example]]
name = "bench_async-std"
required-features = ["use_async-std"]

[[example]]
name = "bench_gio"
required-features = ["use_gio"]

[[example]]
name = "bench_sync"
required-features = ["use_neovim_lib"]

[[test]]
name = "nested_requests"
required-features = ["use_tokio"]

[[test]]
name = "nested_requests_gio"
required-features = ["use_gio", "localspawn"]

[[test]]
name = "connecting"
path = "tests/connecting/mod.rs"
